[build]
builder = "RAILPACK"

[deploy]
startCommand = "gunicorn app:app --worker-class eventlet --workers 1 --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"

[env]
PYTHON_VERSION = "3.11.9"
