[build]
builder = "RAILPACK"
[deploy]
startCommand = "gunicorn app:app --workers 1 --threads 8 --bind 0.0.0.0:$PORT"
healthcheckPath = "/"

restartPolicyType = "ON_FAILURE"

[env]
PYTHON_VERSION = "3.11.9"
